export const loginLabels = {
  Email: "Email",
  email: "email",
  Password: "Password",
  password: "password",
  NewPassword: "newPassword",
  newPassword: "New password",
  ConfirmPassword: "confirmPassword",
  confirmPassword: "Confirm Password",
  signIn: "Sign In",
  verifyEmail: "Verify Email",
  forgotPassword: "Forgot Password",
  forgotPasswordLabel: "Forgot password",
  OTP: "Otp",
  otp: "otp",
};

export const userProfileLabels = {
  file: "file",
  text: "text",
  Name: "Name",
  name: "name",
  PhoneNo: "Phone no",
  phone_number: "phone_number",
  Email: "Email",
  email: "email",
  Gender: "Gender",
  gender: "gender",
  Male: "Male",
  male: "male",
  Female: "Female",
  female: "female",
  Country: "Country",
  country_id: "country_id",
  State: "State",
  state_id: "state_id",
  City: "City",
  city_id: "city_id",
  AddressType: "Address Type",
  address_label: "address_label",
  AddressLine1: "Address Line 1",
  address_line1: "address_line1",
  AddressLine2: "Address Line 2",
  address_line2: "address_line2",
  PostalCode: "Postal Code",
  postal_code: "postal_code",
  EditProfile: "Edit Profile",
  UpdateProfile: "Update Profile",
  Updating: "Updating...",
  Cancel: "Cancel",
  SelectCountry: "Select Country",
  SelectState: "Select State",
  LoadingStates: "Loading states...",
  SelectCity: "Select City",
  LoadingCities: "Loading cities...",
  Home: "Home",
  Work: "Work",
  Other: "Other",
  Profile: "Profile",
};
