export const loginLabels = {
  Email: "Email",
  email: "email",
  Password: "Password",
  password: "password",
  NewPassword: "newPassword",
  newPassword: "New password",
  ConfirmPassword: "confirmPassword",
  confirmPassword: "Confirm Password",
  signIn: "Sign In",
  verifyEmail: "Verify Email",
  forgotPassword: "Forgot Password",
  forgotPasswordLabel: "Forgot password",
  OTP: "Otp",
  otp: "otp",
};
